### ISSUE TITLE
socket hangup errors when attempting to deploy

### ISSUE THREAD

**Issue by rokujoel** [mmratio/roku-deploy#10]
We are experiencing errors when attempting to deploy to a Roku:

spell-check:en-us Can't load en_US: Cannot find dictionary for en_US.
roku-deploy.coffee:44 roku-deploy activated
roku-deploy.coffee:62 zipPackage called.
roku-deploy.coffee:65 Response returned
roku-deploy.coffee:67 Response returned 200
roku-deploy.coffee:86 out directory not found, creating.
roku-deploy.coffee:107 Zipping complete
roku-deploy.coffee:110 http://10.15.237.94/plugin_install
roku-deploy.coffee:121 Request started
roku-deploy.coffee:133 Error: socket hang up(…)
roku-develop.coffee:115 Using config file: C:\Users\MyUsername\AppData\Roaming\Atom\roku-develop-config.json
roku-develop.coffee:504 error Error: socket hang up(…)
roku-develop.coffee:505 response undefined
roku-develop.coffee:506 body undefined
roku-develop.coffee:504 error Error: socket hang up(…)
roku-develop.coffee:505 response undefined
roku-develop.coffee:506 body undefined
roku-deploy.coffee:62 zipPackage called.
roku-deploy.coffee:65 Response returned
roku-deploy.coffee:67 Response returned 200
roku-deploy.coffee:107 Zipping complete
roku-deploy.coffee:110 http://10.15.237.94/plugin_install
roku-deploy.coffee:121 Request started
roku-deploy.coffee:133 Error: socket hang up(…)

**Comment by mmratio** [comment]
Working on getting some support for this.

**Comment by briandunnington** [comment]
@rokujoel Hey Joel - Can you give any more info on your set up? Is the Roku on the same wifi network as your computer? Does the plugin work for other projects and only fail on this specific project? What is the .zip file size? Any other extra information you can provide?

**Comment by rokujoel** [comment]
Hi, thanks for getting back to me.  So apparently it was an antivirus config that specifically affected Atom and Eclipse - IT department modified the config so that it worked again.  We figured it out after a Mac user deleted Kaspersky from his system and that resolved it for him.
